### ISSUE TITLE
After Sorting Items in Inventory, You can longer view its details

### ISSUE THREAD

**Issue by k----n** [CMPUT301F15T10/Exchange#65]

**Comment by touqir14** [comment]
Not sure what issue you are pointing to exactly. Is this an issue that emerged recently due to modification of Inventory activity or is this an old issue(cause by my commits during reading week)? I suggest if you find any of the activity issues regarding inventory or view person activities, let me know and I will look into it.

**Comment by k----n** [comment]
Old issue
